export const SET_PKMN_IMAGE = 'SET_PKMN_IMAGE';
export const SET_PKMN_NAME = 'SET_PKMN_NAME';
export const SET_PKMN_ID = 'SET_PKMN_ID';
export const SET_PKMN_TYPES = 'SET_PKMN_TYPES';
export const SET_PKMN_RESISTANCES = 'SET_PKMN_RESISTANCES';
export const SET_PKMN_WEAKNESSES = 'SET_PKMN_WEAKNESSES';
export const SET_PKMN_ATTACKS = 'SET_PKMN_ATTACKS';
